name: neurofocus
description: "NeuroFocus Development application"
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.35.0
  flutter_launcher_icons: ^0.14.3
  http: ^1.3.0
  permission_handler: ^11.3.1
  supabase_flutter: ^2.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
